# Generated by Django 5.1.2 on 2025-01-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AHome_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captured_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='overlaylog',
            name='design',
        ),
        migrations.RemoveField(
            model_name='overlaylog',
            name='user',
        ),
    ]
